KennaSecurity/toolkit

lib/api.rb
This PR will add in support for more API calls and also fixes an issue with json parsing the results of GET calls.
=> Added more GET call methods for the Ruby API client

tasks/base.rb, tasks/bitsight/lib/bitsight_helpers.rb, tasks/expanse/expanse.rb, tasks/expanse/lib/mapper.rb, tasks/riskiq/lib/client.rb, tasks/riskiq/riskiq.rb
RiskIQ task to translate Digital Footprinting results to KDI (and upload them). Lightly tested, there will likely be a second pass of changes across all the Digifootprint connectors.
Usage: 
```$ bundle exec ruby ./toolkit.rb task=riskiq:riskiq_api_key=$RIQ_API_KEY:riskiq_api_secret=$RIQ_API_SECRET
```
=> Build out the  RiskIQ Task

lib/api/client.rb, lib/helpers.rb, tasks/aws_inspector/aws_inspector.rb, tasks/bitsight/bitsight.rb, tasks/expanse/expanse.rb, tasks/generator/generator.rb, tasks/riskiq/riskiq.rb, tasks/security_scorecard/security_scorecard.rb
Fixes a bug in upload that we ran into on demo this morning.
=> Tweak upload / KDI processing

Containerfile, Dockerfile, README.md, lib/helpers.rb, scripts/entrypoint.sh, toolkit.sh
And let's support other Container Engines such as [Podman](https://podman.io/)!
=> Do not run the toolkit container as the root user

lib/data/mapping/digi_footprint_finding_mapper.rb
Note: also added mapping for ajp_server
Next plan: mapping for the more unique exposures that don't fit into a broader field
=> Mapped Expanse advertisement exposures

lib/data/mapping/digi_footprint_finding_mapper.rb, tasks/bitsight/bitsight.rb, tasks/bitsight/lib/bitsight_helpers.rb, tasks/expanse/lib/mapper.rb, tasks/riskiq/lib/riskiq_helpers.rb, tasks/riskiq/riskiq.rb
Along with general cleanup / testing / fixes.
=> tweaks to DF tasks to improve support for 'port' on vulns

.github/workflows/BundlerAudit.yml, README.md, tasks/ms_defender_atp/readme.md, tasks/snyk/readme.md, tasks/snyk_findings/readme.md
* Apply some minor spelling fixes to things.
* Also renames the Bundler Audit GitHub Action slightly.
* Note: This unfortunately means that the [build history of the previous GitHub Action](https://github.com/KennaPublicSamples/toolkit/actions?query=workflow%3A%22Bunlder+Audit%22) will be lost.
=> [DOC] Spelling fixes

lib/api/client.rb, lib/helpers.rb, lib/kdi/kdi_helpers.rb, tasks/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/ms_defender_atp/ms_defender_atp.rb, tasks/snyk/snyk.rb, tasks/snyk_findings/snyk_findings.rb
added tag for defenders and changed to batch process assets
=> changed to batch process assets

lib/api/client.rb, lib/helpers.rb, lib/kdi/kdi_helpers.rb, tasks/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/ms_defender_atp/ms_defender_atp.rb, tasks/snyk/snyk.rb, tasks/snyk_findings/snyk_findings.rb
Reappying changes that were reverted in #44 
Reverts KennaPublicSamples/toolkit#44
=> Revert "Revert "changed to batch process assets""

Containerfile
@tmgerhart was having some file permission errors so this hopefully fixes that. 
Build output: 
`> Executing task: docker build --pull --rm -f "Dockerfile" -t toolkitjg:latest "." <
[+] Building 20.0s (15/15) FINISHED                                                                                                         
=> [internal] load build definition from Dockerfile                                                                                   0.0s
=> => transferring dockerfile: 1.07kB                                                                                                 0.0s
=> [internal] load .dockerignore                                                                                                      0.0s
=> => transferring context: 2B …
=> Fix user permission

Containerfile
Fixes /opt/app-root/src error the @tmgerhart is exeprincing.
=> Fixes /opt/app-root/src Write Error. 

lib/api/client.rb, lib/helpers.rb, lib/kdi/kdi_helpers.rb, tasks/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/ms_defender_atp/ms_defender_atp.rb
created a few new methods. Changed things around so that there is a call to ONLY upload files and the method returned the json which holds the file number. Code then gathers all the file ids and at the very end a call is done to run the connector and provides the final array of file ids.
=> clean up of atp batching work

Containerfile
This change removes the Kenna user from the container and runs everything as the default user to fix the issues @tmgerhart is running into with the CSV-KDI script.   It also flattens the container file and makes it more readable by removing variables.
=> KISS The Containerfile

lib/kdi/kdi_helpers.rb, tasks/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/ms_defender_atp/ms_defender_atp.rb
allowed for skipping asset check so when loading assets only there isn't a check for dups.
=> lastest change to atp batching

lib/kdi/kdi_helpers.rb, tasks/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/ms_defender_atp/ms_defender_atp.rb
add param for deleting kdi files after upload. revised logic on asset/vuln processing.
=> more atp changes

tasks/csv2kdi/csv2kdi.rb, tasks/csv2kdi/lib/csv2kdi_helper.rb, tasks/csv2kdi/readme.md
This includes one folder/dir (csv2kdi) in the task directory.  All doc is in the read.md file.
=> Added csv2kdi task to repository

Containerfile
In order to make this project more maintainable I have removed the need to pull the Kenna ruby base image from quay and do all needed installation in the containerfile.  This will also help the issue that @dbrothersKenna is running into.
=> Remove The Need For Kenna Base Image

tasks/csv2kdi/csv2kdi.rb, tasks/csv2kdi/lib/csv2kdi_helper.rb, tasks/csv2kdi/readme.md
This fix is required to avoid rathole caused from ruby csv processing byte order mark.
=> Update 2nd csv read to include BOM and update readme

lib/helpers.rb, tasks/csv2kdi/csv2kdi.rb, tasks/csv2kdi/lib/csv2kdi_helper.rb, tasks/csv2kdi/readme.md, tasks/csv2kdi/tk_meta.csv
1) Update to include appsec findings logic.
2) Added updated readme
3) Added sample meta file
4) Frozen literal/variable logic to enable readme help logic to work
=> Update csv2kdi to include findings

tasks/expanse_issues/lib/client.rb
This should fix an issue I noticed where priority filters were not being respected.
=> Expanse filter name should be priority rather than priorities

tasks/csv2kdi/csv2kdi.rb, tasks/csv2kdi/lib/csv2kdi_helper.rb, tasks/csv2kdi/readme.md
Leveraging common processes for batches and updating documentation.
=> Leveraging common processes for batching task runs

tasks/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/veracode_asset_vulns/veracode_asset_vulns.rb, tasks/veracode_findings/lib/veracode_client.rb
Veracode Findings Updates:
- Add Tagging
- Add locator functionality to submit file and URL
- Add Finding Status to submission
New Veracode Asset-Vulns task
- based on Findings model above.
=> Veracode Findings updates and new Veracode Asset-Vulns task

tasks/csv2kdi/lib/csv2kdi_helper.rb
=> Error handling corrections for csv2kdi helper

tasks/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/veracode_findings/lib/veracode_client.rb
Was led to incorrect syntax by Rubocop.
=> Bug Fix - Correcting Syntax

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
1. Updated Asset File locators to use full path instead of file name.
2. Fixed bug that was losing "business unit" tag.
=> Veracode Updates

tasks/utilities/csv2kdi/readme.md, tasks/utilities/csv2kdi/tk_meta.csv
Doc updates due to new directory structure.
=> meta file and doc update

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_asset_vulns/veracode_asset_vulns.rb
1. Added Solution to top of details until Solution KDI bug is resolved.
2. Also adjusted incoming scanner score to match the Kenna scale. Adjusting scanner score *2 and then connector will multiply times 10 on import. (i.e. 1-5 => 20-100)
=> Added Solution to top of Details, also Score Update

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
=> Added Ext ID to Asset

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb, tasks/connectors/veracode_findings/veracode_findings.rb
Veracode Updates:
- Veracode Status Mapping
- Added Recommendations/Solutions in Additional Info Section for Findings.
- Formatting Corrections within the Additional Info Section
=> Veracode Status Mapping and Misc Updates

README.md
=>  README-Update-JG

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb
Add SCA Data to Veracode tasks
=> Add SCA Data to Veracode tasks

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb
=> Fixes to CVE Identifiers

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb
Was previously using Finding Category which resulted in some of them getting deduped and overwriting one another to the wrong base CWE.  Better to just keep them on the CWE level.
=> Change VDef ID to CWE

lib/api/client.rb, tasks/base.rb
Added Task Name to User-Agent Setting.
=> User-Agent Update - Add Task Name

tasks/base.rb
Corrected code to update User-Agent
=> Bug Fix in Task Tracking

tasks/connectors/contrast/contrast.rb, tasks/connectors/contrast/lib/client.rb
Misc corrections per Linter errors.
https://github.com/KennaSecurity/toolkit/runs/2822866084?check_suite_focus=true
=> Linter Error corrections for Contrast Task

tasks/connectors/contrast/contrast.rb, tasks/connectors/contrast/lib/client.rb, tasks/connectors/contrast/readme.md
required changes to toolkit.rb are needed before this code can be checked in.
=> updates for Contrast Toolkit

lib/api/client.rb, tasks/utilities/user_role_sync/user_role_sync.rb
The fix is within the scope.  However, it probably would be useful to get the header in one spot.
Also, I will create a ticket to update the version with GitHub hooks.
=> Modified User-Agent to standard

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_asset_vulns/veracode_asset_vulns.rb
- Added optional Score mapping
- Added optional Custom Field Exclusions
- Added MANUAL scan type
- Realigned Veracode Issue # to Scanner Iderntifier
- Converted to KDI v2 JSON to support realigned Issue #
- Set Page Size Limit of 500 and removed requirement of parameter
=> Veracode-Updates

tasks/utilities/user_role_sync/user_role_sync.rb
Updated User-Role-Sync to support new MRPU functionality
=> Updating for MRPU endpoint updates

README.md, tasks/connectors/aqua/README.md, tasks/connectors/aqua/aqua.rb, tasks/connectors/aqua/lib/aqua_helper.rb, tasks/readme.md
This is the beta code for Aqua connector that extracts Image and Container vulnerability data from Aqua and uploads to the Kenna platform.
=> Aqua Connector for Kenna toolkit

tasks/utilities/user_role_sync/readme.md
Update User-Role-Sync readme.md.
=> Update User-Role-Sync readme.md.

initialize/enumerable.rb, initialize/presence.rb, lib/toolkit.rb, spec/enumerable_spec.rb, spec/presence_spec.rb
- #blank?
- #present?
- #index_by
=> This commit adds the following methods present in active_support:

tasks/connectors/netsparker/lib/netsparker_client.rb, tasks/connectors/netsparker/netsparker_readme.md, tasks/connectors/netsparker/netsparker_task.rb, tasks/utilities/netsparker/netsparker.rb
User can filter by schedule ID and severity and also indicate the batch_size.
=> Netsparker connector for Kenna, first commit.

tasks/connectors/acunetix360/acunetix360_readme.md, tasks/connectors/acunetix360/acunetix360_task.rb, tasks/connectors/acunetix360/lib/acunetix360_client.rb
This connector is exactly the same as Netsparker so we could do something to have only one version. I can't guess how both will evolve in the future.
=> Acutenix360 new connector, first commit.

tasks/connectors/snyk_v2/readme.md, tasks/connectors/snyk_v2/snyk_v2.rb
…pe" (string: ["vulns", "findings"])
=> Rename "use_findings" param (boolean) to the more readable "import_type"

tasks/connectors/jfrog/jfrog_readme.md, tasks/connectors/jfrog/jfrog_task.rb, tasks/connectors/jfrog/lib/jfrog_client.rb
This is the first commit for the connector. Tested ok against kenna .
=> JFrog-connector, first commit

tasks/connectors/acunetix360/acunetix360_task.rb, tasks/connectors/acunetix360/lib/acunetix360_client.rb, tasks/connectors/bugcrowd/bugcrowd_task.rb, tasks/connectors/bugcrowd/lib/bugcrowd_client.rb, tasks/connectors/burp/burp_task.rb, tasks/connectors/burp/lib/burp_client.rb, tasks/connectors/jfrog/jfrog_task.rb, tasks/connectors/jfrog/lib/jfrog_client.rb, tasks/connectors/qualys_was/qualys_was.rb, tasks/connectors/veracode/lib/veracode_client.rb, tasks/connectors/veracode/veracode_task.rb
Some more tasks changed to the pattern implemented by Ben
=> Fail tasks on api failure

tasks/connectors/acunetix360/acunetix360_task.rb, tasks/connectors/netsparker/netsparker_task.rb
This was found during the mappings file work
=> Added cwe_identifiers to vuln_def for both identical connectors.

tasks/connectors/bugcrowd/bugcrowd_task.rb, tasks/connectors/bugcrowd/lib/bugcrowd_client.rb, tasks/connectors/bugcrowd/lib/cwe.json
The mappings file is downloaded from GitHub, but, a local copy is keep just in case the project or file is moved.
=> Adds CWE mappings from Bugcrowd's VTR project.

tasks/connectors/appscan_cloud/appscan_cloud_readme.md, tasks/connectors/appscan_cloud/appscan_cloud_task.rb, tasks/connectors/appscan_cloud/lib/appscan_cloud_client.rb
There are some TO-DO's to resolve before considering it  OK for testing.
We need a valid license in order to get all data fields and correctly map the locator fields.
=> This commit adds a new AppScan on Cloud connector.

tasks/connectors/veracode/lib/veracode_client.rb, tasks/connectors/veracode/veracode_readme.md, tasks/connectors/veracode/veracode_task.rb
Now the assets are uploaded in batches (default 500).
=> Add batch_size to Veracode combined task

.github/workflows/nativeruby.yml
Action Fix To Point At Master Branch
=> Action Fix To Point At Master Branch

tasks/connectors/veracode/lib/scan_type.rb, tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb, tasks/connectors/whitehat_sentinel/lib/api_client.rb
These start to show after rubocop upgrade.
=> Some corrections as suggested by Rubocop.

codeql-analysis.yml
Adds a github action to run codeql analysis on toolkit ruby code.
=> Security: Create codeql-analysis action to run against toolkit ruby code

tasks/connectors/github_secret_scanning/github_secret_scanning_task.rb, tasks/connectors/github_secret_scanning/lib/github_secret_scanning_client.rb, tasks/connectors/github_secret_scanning/readme.md
This is the first working commit
=> GitHub secret scanning

tasks/connectors/github_code_scanning/github_code_scanning_task.rb, tasks/connectors/github_code_scanning/lib/github_code_scanning_client.rb, tasks/connectors/github_code_scanning/readme.md
=> GitHub Code Scanning connector first commit

tasks/connectors/snyk_v2/snyk_v2.rb
First attempt added as asset tag.
=> Add org data to Snyk_v2.

tasks/connectors/hackerone/hackerone_task.rb, tasks/connectors/hackerone/lib/hackerone_client.rb, tasks/connectors/hackerone/readme.md
maybe something needs to be fixed
=> Hackerone connector

lib/helpers.rb, tasks/connectors/sysdig/lib/mapper.rb, tasks/connectors/sysdig/lib/runtime_mapper.rb, tasks/connectors/sysdig/lib/static_mapper.rb, tasks/connectors/sysdig/lib/sysdig_client.rb, tasks/connectors/sysdig/readme.md, tasks/connectors/sysdig/sysdig_task.rb, util/make_readme
Working static and runtime issues import controlled by import_type parameter.
Filters by severity.
Sysdig pagination supported.
Kenna batching supported.
=> Sysdig connector

README.md
documentations about running Toolkit docker images on GitHub Actions
=> Update readme with GitHub Actions docs

.rubocop.yml, initialize/object.rb, lib/helpers.rb, lib/toolkit.rb, spec/tasks/connectors/whitehat_sentinel/lib/api_client_spec.rb, spec/tasks/connectors/whitehat_sentinel/lib/mapper_spec.rb, spec/tasks/connectors/whitehat_sentinel/whitehat_sentinel_task_spec.rb, spec/toolkit/base_task_spec.rb, tasks/base.rb, tasks/connectors/appscan_enterprise/appscan_enterprise_task.rb, tasks/connectors/appscan_enterprise/lib/appscan_enterprise_client.rb, tasks/utilities/example/example.rb
Please, smoke test all most important connectors before merge.
=> Parameters changes (needed for cloudfront)

tasks/connectors/hackerone/readme.md
Program name parameter was wrong in the readme. This updates  it to the correct one
=> Hackerone readme update

.gitignore, tasks/connectors/insight_appsec/insight_appsec_task.rb, tasks/connectors/insight_appsec/lib/insight_appsec_client.rb, tasks/connectors/insight_appsec/readme.md
=> Insight AppSec conector

tasks/connectors/wiz/lib/issues_mapper.rb
Changed the owner field that maps to assets owner for issues
=> [CON- 1105] Change wiz assets owner

tasks/connectors/wiz/lib/issues_mapper.rb, tasks/connectors/wiz/lib/mapper.rb, tasks/connectors/wiz/lib/vulns_mapper.rb, tasks/connectors/wiz/lib/wiz_client.rb, tasks/connectors/wiz/readme.md, tasks/connectors/wiz/wiz_task.rb
- Added new parameters for hostname custom mapping
- Added parameter to increase kenna_batch_size
- Only send totalCount for the first request for performance reasons (WIZ endpoint)
=> [CON-1151][TOOLKIT] Custom hostname mapping

README.md
[CON-1227](https://kennasecurity.atlassian.net/browse/CON-1227)
=> Update Toolkit README file. Add info about Github Issues.

README.md
=> CON-1243 add feature request email to readme

Gemfile.lock, tasks/readme.md
clarification on Maintained by vs created by.
=> Update readme.md to clarify support verbiage: Maintain vs creation

tasks/connectors/wiz/readme.md, tasks/connectors/wiz/wiz_task.rb
Changed count of vulnerabilities API so each page can consist max 5000 vulnerabilities (500 vulnerabilities was before)
=> Changed count of vulnerabilities API so each page can consist max 5000

tasks/connectors/bugcrowd/lib/bugcrowd_client.rb, tasks/utilities/csv2kdi/csv2kdi.rb, tasks/utilities/csv2kdi/tk_meta.csv, tasks/utilities/netsparker/netsparker.rb
Allow multi cwe/cve per line.  Updated metafile doc for more clarity
=> Update doc and and code csv2kdi

tasks/connectors/armis/readme.md
[CON-1549](https://kennasecurity.atlassian.net/browse/CON-1549)
- Move Support section to the top of the readme.md file.
- Add text to the Support section: “All issues and inquiries relating to this toolkit implementation must contact Armis support.”
=> Move "Support" section to the top and add some text

tasks/readme.md
Certification of Wiz and Contrast. Meet criteria for certification (see internal thread). 
Remove Expanse (not expanse issues) as users should leverage Expanse_issues as it is the newest version. 
Added Armis by Armis
Added GitHub Secret Scanning by GitHub
=> readme changes

tasks/utilities/csv2kdi/csv2kdi.rb, tasks/utilities/csv2kdi/lib/csv2kdi_helper.rb, tasks/utilities/csv2kdi/tk_meta.csv
Addition of Container and Image locators
=> Addition of Container and Image locators

tasks/utilities/csv2kdi/csv2kdi.rb
Add Backwards Compatibility for Container Image addition
=> Add Backwards Compatibility for locator additions

tasks/connectors/snyk_v2/snyk_v2_task.rb
Jira: [CON-1767](https://kennasecurity.atlassian.net/browse/CON-1767)
Fixes bugs that arise in the Lewis's clients.
Screenshots:
=> Successful run snyk with new token

tasks/connectors/wiz/lib/vulns_mapper.rb
Gets the EC2 Id in the Wiz connector if it is available and the cloud platform is AWS
=> Get EC2 instance ID in WIZ

spec/tasks/connectors/wiz/lib/vuln_mapper_spec.rb, tasks/connectors/wiz/lib/vulns_mapper.rb
Jira [CON-2695](https://kennasecurity.atlassian.net/browse/CON-2695)
[CON-2695]: https://kennasecurity.atlassian.net/browse/CON-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CON-2695] Add Detailed Name and Detection Method to vuln details

tasks/connectors/lacework/lib/lacework_helper.rb
Check against integer as opposed to string.
=> Check against integer

tasks/connectors/cylera/readme.md
Updated readme file for Cylera connector.
Added instructions on how to run Cylera connector in incremental mode.
=> Update Cylera readme

tasks/connectors/cylera/readme.md
I hope I was able to update it correctly. I spend sometime with Steve. I think it helped...
=> @bodubas @jgarber-cisco

tasks/readme.md
Zeh asked me to update it because Feedback just came in from the field that this list needs to be updated.
=> Updated Toolkit Connector Information readme.md

spec/fixtures/digital_footprint/bitsight_findings_page_1.json, spec/fixtures/digital_footprint/bitsight_findings_page_2.json, spec/fixtures/digital_footprint/bitsight_portafolio.json, spec/fixtures/digital_footprint/bitsight_validate_key.json, spec/tasks/connectors/digital_footprint/bitsight_spec.rb, tasks/connectors/digital_footprint/bitsight/bitsight.rb, tasks/connectors/digital_footprint/bitsight/lib/bitsight_helpers.rb
=> CON-3812/fix bitsight web_appsec findings

.github/workflows/BundlerAudit.yml, .github/workflows/nativeruby.yml, .rspec, Gemfile, Gemfile.lock, spec/rspec_helper.rb, spec/tasks/connectors/aws_inspector2/aws_inspector2_spec.rb, spec/tasks/connectors/snyk_v2/snyk_v2_stubs.rb, spec/tasks/connectors/snyk_v2/snyk_v2_task_spec.rb, spec/tasks/connectors/veracode_findings/veracode_findings_stubs.rb, spec/tasks/connectors/veracode_findings/veracode_findings_task_spec.rb, spec/tasks/connectors/whitehat_sentinel/whitehat_sentinel_task_spec.rb, spec/tasks/connectors/wiz/lib/wiz_client_spec.rb, tasks/connectors/digital_footprint/security_scorecard/security_scorecard.rb, tasks/connectors/snyk/snyk.rb, tasks/connectors/snyk_findings/snyk_findings.rb
1. Fix Bundler Audit [problem](https://github.com/KennaSecurity/toolkit/actions/runs/7223462232/job/19682821554) with bundler version and ruby version (unblocks #522)
2. Fix #492 specs aren't run in GitHub Actions
=> Fix GitHub Actions issues

spec/tasks/connectors/aws_inspector2/aws_inspector2_spec.rb, tasks/connectors/aws_inspector2/aws_inspector2.rb, tasks/connectors/aws_inspector2/readme.md
AWS lambda findings are not supported by the task but cause it to fail for all findings
Filter findings by supported resources (container and ec2)
=> SUP-1567 Undefined method ip_v4_addresses for NilClass

tasks/connectors/aqua/aqua.rb, tasks/connectors/aqua/lib/aqua_helper.rb
[Issue](https://github.com/KennaSecurity/toolkit/issues/550)
Add  SaaS  regions to Aqua connector
=> Add regions to aqua

tasks/connectors/aqua/lib/aqua_helper.rb
[Issue](https://github.com/KennaSecurity/toolkit/issues/550)
Fix for working against an Aqua on-prem version
1 variant aqua:
2 variant aqua (cloud):
=> Fix for working against an Aqua on-prem version

.circleci/config.yml
Builds and pushes to Devhub Artififactory.
Circle Context added devhub-artifactory
=> circle config to push to devhub artifactory

codecov.yml, lib/helpers.rb, spec/rspec_helper.rb
Don't want the spec directory at 100% coverage affecting the overall project score!
=> Tweak what Simplecov ignores

lib/http.rb
Hello sorry, 
I found out that the previous PR has typo. 
Create a new one for review.
=> SUP-1778 correct syntext error

tasks/connectors/digital_footprint/security_scorecard/lib/client.rb, tasks/connectors/digital_footprint/security_scorecard/security_scorecard.rb
1. Remove the redundant to_s
2. current code logic can result in pulling assets which have all hostname, url, and ip_address empty which result in fail connector runs.
=> SUP-1821-whitecase-ssc
