KennaSecurity/toolkit

lib/api/client.rb, lib/helpers.rb, lib/http.rb, lib/kdi/kdi_helpers.rb, lib/toolkit.rb, tasks/microsoft_atp/lib/microsoft_atp_helper.rb, tasks/microsoft_atp/microsoft_atp.rb
All kudos to @lindambrown for building this, this is just a cleanup pass on her original script.
Note that this does not yet handle pagination and is only tested with a very small set of data. That said, is working against the ATP apis now: 
```
jcran toolkit develop [20200605]$ cat /bundle exec ruby ./toolkit.rb task=microsoft_atp:atp_tenant_id=$ATP_TENANT_ID:atp_client_id=$ATP_CLIENT_ID:atp_client_secret=$ATP_SECRET
Running: Kenna::Toolkit::MicrosoftAtp
[+] (20200605104607) Setting kenna_api_host to default value: api.kennasecurity.com
[+] (20200605104607) Setting output_directory to default value: output/microsoft_atp
[+] (20200605104607) Got option: task: microsoft_atp
[+] (20200605104607) Got option: atp_tenant_id: 5******903
[+] (20200605104607) Got option: atp_client_id: 5*****095 …
```
=> Add a prelim task to query microsoft ATP

tasks/expanse/lib/mapper.rb
per expanse, changed where I was getting the tags from because the other node was deprecated.
=> Expanse tagging

tasks/expanse/lib/mapper.rb
This had issues when cloud_exposure_types is explicitly provided as an arg.  Excellent details on this issue provided by @andrew-expanse in #39.
Fixes #39
=> Expanse: Properly split cloud_exposure_types into array

lib/helpers.rb
Added required annotation and default value to task specific help for tasks  (task=taskname:help)
This will provide more context for users to create command lines directly from their terminal without referencing the read.md
=> Added required annotation and default value to task specific help for tasks  (task=taskname:help)

tasks/riskiq/lib/riskiq_helpers.rb, tasks/riskiq/riskiq.rb
This commit is designed to make the RIQ open ports info available in cases of very large attack surface by requiring that each system have less than 1200 ports open and limiting the detail port info.
=> Limit systems with open ports >1200 and make detailed info unaviailable

Gemfile, Gemfile.lock
This PR, unfortunately, downgrades rubocop from 1.3.1 to 0.82.0[1] (which dates to 2020-04-16). This will ensure that whether you get rubocop feedback locally via the command line or your editor, or remotely via our Github code linting action, you will get the same results.
In my view, there aren't any new "cops" introduced between 0.82.0 and 1.3.1 that are super important for our own needs, so I don't think this downgrade has a material impact on our linting.
Once the upstream super-linter project that powers our action supports a more recent version of rubocop, we can upgrade both that and rubocop in this repo in tandem.
Rubocop is 100% clean as of this PR, reporting no issues.
https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0820-2020-04-16
=> Temporarily downgrade rubocop to 0.82.0, to match super-linter

.dockerignore, Containerfile
These changes include adding a [dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file to control what we copy to the container in a better manner. 
Only installing production gems in the container using: `RUN bundle install --without development test`
Not installing `Python3` since there is no python code in the repo.  These changes slims the image down 154MB.
=> Docker Clean-up

Gemfile, lib/kdi/kdi_helpers.rb
Based on some feedback in #dev_internal [here](https://kennasecurity.slack.com/archives/C012YTRLQNQ/p1610395067112100?thread_ts=1610393051.108900&cid=C012YTRLQNQ) I pulled a few operations out of the `@assets.lazy.find{}` loop, so that they are done only once, not once for each member of `@assets`.
I also consolidated some duplicated code into a small method.
Full disclosure: I did not formally measure the performance improvement here, nor did I retest the functionality.
=> A few small optimizations to kdi_helpers

README.md
We will continue to build on quay to not break anyone using that at this point.
=> Update README.md to point to DockerHub by default.

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb
Omitting CWE when CVE exists. Backend only takes one.
=> Omit CWE when CVE exists

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_asset_vulns/veracode_asset_vulns.rb
1. **Removed Line Numbers from File locator** - Was causing problems with Asset deduplication. 
2. **Standardized added tags with "veracode_"**
- veracode_scan_type
- veracode_app
- veracode_bu
3. **Add new parameter to allow for specifying the scan types to be pulled.** Comma-delimited list defaulted to all types ("STATIC,DYNAMIC,SCA")
=> Veracode Asset Vuln Enhancements

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
1. Revert filename_locator back to filename rather than filepath.  Filepath contained build numbers which caused new a new asset to be created each build.
2. Add veracode_bc: tag for Business Criticality
3. Add HREF value as solution for CVE and SRCCLR findings.
=> Veracode av updates

README.md, tasks/connectors/lacework/lacework.rb, tasks/connectors/lacework/lib/lacework_helper.rb, tasks/connectors/lacework/readme.md
This PR adds a connector to the toolkit for retrieving host and vulnerability data from the lacework api.  It pipes that data into Kenna using the KDI and Kenna API.  This is my first foray into the toolkit, so feedback welcome!
=> Build Lacework into the toolkit

tasks/connectors/lacework/lacework.rb, tasks/connectors/lacework/lib/lacework_helper.rb
Fixes a couple formatting issues:
- there were duplicate hash keys being created as a result of stringified keys vs symbols.  This PR addresses that by converting all keys to strings
- breaks up the multistep vulns_by_host loop for better readability
- only pull back Active vulnerabilities and let Kenna handle vulnerability autoclose
=> Lacework toolkit: code format updates, only pull back Active CVEs from Lacework

Containerfile
The ruby base image we are using has went EOL.  We were running Ruby 2.6.6 on Debian 10.09, this change updates the image to Ruby 2.6.7 on Debian 10.10.
=> Update Container Base Image From EOL Version. 

lib/http.rb, toolkit.rb
Changes to toolkit.rb are needed because even with quotes, the current code will drop equal signs at the end of a string. In the sample case, an API key had == at the end and those 2 characters were dropped even with quotes around the string. Code has been tested with param separated by both space and colon.
=> required changes

lib/api/client.rb, tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
Add Missing Assets Functionality
This will help to help to auto-close vulns for assets that totally stop reporting, because of total remediation.
=> Add Missing Assets Functionality

tasks/base.rb
Obscure "_id" parameters:
This update will additionally obscure parameters that contain "_id".
=> Obscure "_id" parameters

tasks/connectors/cobaltio/cobaltio.rb, tasks/connectors/cobaltio/readme.md
Following up on #201, this add support for importing data from Cobalt.io as _findings_. This time the implementation is based off of [the Contrast task](https://github.com/KennaSecurity/toolkit/tree/master/tasks/connectors/contrast). Note that I changed the default import from vulns to findings as the latter betters suites the Cobalt data format.
On top of that, I
- removed an unused option (3b0b9c9abc4e8604567e9d94b38ecfd954c5a13d),
- added a missing option to the tasks metadata (ae48bca939a62ca327437f184ed3f2528b31345d), and
- added the `status` and `scanner_score` fields for vulns.
=> Add support for findings to Cobalt.io task

lib/helpers.rb, spec/tasks/connectors/whitehat_sentinel/whitehat_sentinel_task_spec.rb, tasks/base.rb, tasks/connectors/aws_guardduty/aws_guardduty.rb, tasks/connectors/aws_inspector/aws_inspector.rb, tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/whitehat_sentinel/whitehat_sentinel_task.rb
As we move to a world where the toolkit is run in hosted containers, having a non-zero status code will make failures easier to detect.  Passing a status value to [`exit`](https://ruby-doc.org/core-2.6.4/SystemExit.html) causes the Ruby process to terminate with the given value as it's status code.
=> Add a helper method to fail tasks with a non-zero status code

tasks/connectors/bitsight/bitsight.rb, tasks/connectors/expanse/expanse.rb, tasks/connectors/expanse_issues/expanse_issues.rb, tasks/connectors/security_scorecard/security_scorecard.rb, toolkit.rb
After #242, I found a few more places that can call `fail_task` when exiting.  They were missed initially because they were calling `return` instead of `exit`.
Additionally, early on in the script we will break if given improperly formatted command line arguments, we should exit with a non-zero status code there, also.
=> Exit with non-zero status code in a few more places

tasks/connectors/edgescan/lib/edgescan_asset.rb, tasks/connectors/edgescan/lib/edgescan_definition.rb, tasks/connectors/edgescan/lib/edgescan_location_specifier.rb, tasks/connectors/edgescan/lib/edgescan_vulnerability.rb
- Updated `scanner_type` to be either `EdgescanNet` or `EdgescanApp` depending on the layer of the vulnerability.
- Made it so assets no longer set `application`.
We also had two quick questions that came up during development.
Just wanted to verify if we read you right for points `a.ii` and `b.ii`:
We've changed it so that assets no longer have an application ID. This means that they will no longer be grouped together in the Applications view on the frontend. We've made this change to both the network and application assets. 
Points `a.i` and `b.i` are fine for the majority of cases:
We just wanted to double check with you about a rare case. 
Assets on Edgescan can also have IP block locators. For example an asset may have a locator that looks like this: `192.168.0.1-50`. This would mean …
=> Tweak what information Edgescan sends to Kenna.

tasks/connectors/bugcrowd/bugcrowd_task.rb
I found it had the same problem that the other connectors pushed by me. Now is fixed.
=> Fixed wrong usage of kdi_connector_kickoff

tasks/connectors/aqua/aqua.rb, tasks/connectors/aqua/lib/aqua_helper.rb, tasks/connectors/burp/burp_task.rb, tasks/connectors/burp/lib/burp_client.rb, tasks/connectors/cobaltio/cobaltio.rb, tasks/connectors/contrast/contrast.rb, tasks/connectors/contrast/lib/client.rb, tasks/connectors/edgescan/edgescan.rb, tasks/connectors/edgescan/lib/edgescan_api.rb, tasks/connectors/lacework/lacework.rb, tasks/connectors/lacework/lib/lacework_helper.rb, tasks/connectors/ms_defender_atp/lib/ms_defender_atp_helper.rb, tasks/connectors/ms_defender_atp/ms_defender_atp.rb, tasks/connectors/ms_defender_tvm/lib/ms_defender_tvm_helper.rb, tasks/connectors/ms_defender_tvm/ms_defender_tvm.rb, tasks/connectors/nozomi/nozomi.rb, tasks/connectors/riskiq/lib/riskiq_helper.rb, tasks/connectors/riskiq/riskiq.rb, tasks/connectors/snyk/snyk.rb, tasks/connectors/snyk_findings/snyk_findings.rb, tasks/connectors/snyk_v2/snyk_v2.rb, tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb, tasks/connectors/veracode_asset_vulns/veracode_asset_vulns.rb, tasks/connectors/veracode_findings/lib/veracode_client.rb, tasks/connectors/veracode_findings/veracode_findings.rb, tasks/connectors/wiz/lib/wiz_client.rb, tasks/connectors/wiz/wiz_task.rb
Following up on #242 and #243, this PR detects when a task's initial API call fails, assumes the failure is due to incorrect credentials and uses `fail_task` to exit the task with an error message and non-zero status code.
Most tasks use the `http_get` and `http_post` helper methods, which retry on failure but swallow errors.  When retries are exhausted, those helpers simply return `nil` instead of raising an error.  Instead of changing that design, which feels very invasive, this PR detects when we receive a `nil` response and assumes it is due to an error.  Additionally, it only tries to detect failure on the task's first API call.  If we have valid creds but the API breaks partway through we'll likely get a gross failure, but that seems less likely than being given bad creds.
=> Cleanly handle initial API failures for tasks

lib/api/client.rb, lib/helpers.rb, spec/tasks/connectors/whitehat_sentinel/whitehat_sentinel_task_spec.rb
Two pieces to this change:
1. The Kenna API client now grabs the results of the ConnectorRun from the API once the connector is no longer running and returns that as the result of `run_files_on_connector`
2. `run_files_on_kenna_connector` inspects that API response and if the connector run was not successful, it will print a message and exit with a non-zero status code.  This will help us detect unsuccessful CRs when the toolkit is running inside of a hosted container.
=> Fail the task if we can't upload to Kenna or if the resulting ConnectorRun fails

tasks/connectors/checkmarx_sast/README.md, tasks/connectors/checkmarx_sast/checkmarx_sast.rb, tasks/connectors/checkmarx_sast/lib/checkmarx_sast_helper.rb
This toolkit brings in data from Checkmarx SAST (https://partners9x.checkmarx.net/cxrestapi/)
To run this task you need the following information from Checkmarx SAST:
1. Username
2. Password
3. Client ID
4. Client Secret
5. grant_type
6. scope (optional)
- Get a list of Projects currently present in the user's Checkmarx SAST account.
- Get a list of Scans in the user's Checkmarx SAST account associated with each Project.
- Generate Report Id on each scan.
- Get a list of scan reports using newly generated above report id.
- Output a json file in the Kenna Data Importer (KDI) format.
- Post the file to Kenna if API Key and Connector ID are provided
=> Implemented Checkmarx SAST connector

util/make_readme
Tired of writing Task::metadata and readme.md with the same contents?
Forgot update readme.md after add/remove parameter?
Now you can automatically generate a readme.md file based on Task::metadata contents using ./util/make_readme task=task_name
=> Make readme.md using task metadata

tasks/connectors/github_dependabot/github_dependabot.rb, tasks/connectors/github_dependabot/lib/github_dependabot_client.rb
Fixed error when retrieving alerts from a repo present in the organization but not owned by it.
Enhance error message when input owner name is wrong but token exists.
Added log for each processed repository
=> GitHub Dependabot Fixes

tasks/connectors/sysdig/lib/runtime_mapper.rb
Changed asset_type => "container" to only an external_id because the vendor says they are not always containers.
=> Sysdig asset_type changes

tasks/utilities/netsparker/netsparker.rb
This is a deprecated task, and had a duplicate task ID causing this process to run instead of the updated netsparker task in the connectors folder.
=> Update Netsparker task ID

tasks/connectors/bugcrowd/bugcrowd_task.rb
include_duplicated param was nil and in ruby acted as false but when passed as parameter to BugCrowd it output as "" and endpoint raised 400 Bad requested due to an expected boolean value in the param.
=> Fix include_duplicated param

.rubocop.yml, initialize/object.rb, lib/http.rb, tasks/base.rb
This change adds more details to logging about API call exceptions. This will help clients know whether the failures they see logged are in their scanner or Kenna.
=> Add verbosity to API exception logging to help clients/support

tasks/connectors/ms_defender_tvm/readme.md
Updated link (previous link redirects to new link, and added information about the change in name from MSFT Defender TVM to Microsoft 365 Defender
=> Update readme.md for MSFT Defender TVM

.github/workflows/nativeruby.yml
Problem: Native ruby Github action fails because one command is deprecated.
Solution: change command as per example in deprecation warning
=> Set local environment to get rid of deprecation

Gemfile.lock, tasks/connectors/wiz/readme.md
The documentation currently indicates that we're able to pull vulnerabilities detected after a given date, when really we're only able to pull vulnerabilities created after a given date.
=> Correct Wiz.io documentation

Gemfile.lock, tasks/connectors/edgescan/edgescan.rb, tasks/connectors/edgescan/lib/edgescan_api.rb
Clients require the ability to import vulnerabilities based on layer type, `application` and `network`.
Bug also found when attempting to create Kenna findings.
- Added 2 flags `include_network_vulnerabilities`, and `include_application_vulnerabilities` to allow the separation of vulnerabilities when importing. Both set to `true` by default.
- Fixed bug where Kenna findings were not being created when `create_findings` flag was set to `true`.
=> Update Edgescan Connector

tasks/connectors/veracode_asset_vulns/readme.md, tasks/connectors/veracode_asset_vulns/veracode_asset_vulns.rb, tasks/connectors/veracode_findings/readme.md, tasks/connectors/veracode_findings/veracode_findings.rb
**Problem**
Clients whose Veracode applications have double quotes in the name are seeing those tasks fail. We put those terms within another set of double quotes and this messes up tokenization of search terms.  This has long been an issue in Kenna UI and is unlikely to be solved soon.
**Solution**
Most clients work around this by using single quotes in the field values when double would otherwise be used. This change converts app names to single quotes after the initial pull of application data. This should not change the data in any other way since we always pull further data from Veracode using the apps Id instead of name.
=> Convert quotes because doubles don't play nice w/ our queries

README.md
QAs upload files to production if they want to see the output in UI.
Add a README section about how to run a task so that the local api host can accept toolkit's requests.
=> Add info about how to upload to local api host

tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
That pr fixes a issue when trying to run a specific Veracode task without kenna api
Before:
Change:
=> Fix: guard to allow to execute without kenna api

tasks/utilities/csv2kdi/csv2kdi.rb
Try to fix the error "illegal quoting.
Try №1
with `liberal_parsing: true`
=> Fix illegal quoting for csv2kdi with liberal_parsing parameter

lib/api/client.rb
On the connector file upload endpoint Kenna returns a 422 in a very generic failure scenario when the file could not be persisted in Kenna. This can be a sporadic problem, so we should not immediately fail toolkit run attempts when this happens..
Another failure saw errors when we try to process a seeming empty response from Kenna. The current response processing doesn't correctly check for success in the response so some failures slip by
-add UnprocessableEntity to a rescue statement with retries.
-check "success" field assuming it's string value
-treat lack of "success":"true" in response as a generic failure (which does retries)
=> retry 422, treat success field as string

tasks/connectors/ntt_sentinel_dynamic/lib/api_client.rb, tasks/connectors/ntt_sentinel_dynamic/ntt_sentinel_dynamic.rb
Client was seeing 401 unauthorized errors using the Whitehat/Sentinel toolkit task despite providing valid api token. Support discovered that the params provided to RestClient were not in the right form. After resolving that I ran into two other problems:
1. The task tries to "validate" the api token using an endpoint that doesn't seem to be documented and was returning 404
2. Accept header was not passed in correctly, so we were getting data back in unexpected XML
1. fix params format to be {header1: value1, header2: value2, params:{urlparam1: "value1", urlparam2: "value2"}}
2. remove invalid validation call step - we can expect a 401 in later calls if there's a problem with the token
- see: `https://apidocs.whitehatsec.com/whs/reference/`
- was using a GET to '/' endpoint
3. specify …
=> SUP-980-sentinel_fix_params_and_remove_api_check_step

Gemfile.lock, tasks/connectors/digital_footprint/expanse_issues/lib/expanse_issues_mapper.rb
[CON-1551](https://kennasecurity.atlassian.net/browse/CON-1551)
1) Run the task with the optional parameter issue_types=MissingCacheControlHeader
Expected
The run should fetch only vulns related to the issue_type and create only one file
Actual
The run creates 4 files with same data
=> Fix simular files for expanse_issues

lib/http.rb
A client hit an error running the toolkit when some api calls returned an Errno::ECONNREFUSED exception that we are not handling correctly:
```
[!] (20220901194247) Exception! Failed to open TCP connection to aqua.prod.us-west-2.aws.fico.com:443 (Connection refused - connect(2) for 52.89.54.93:443)
/opt/app/toolkit/lib/http.rb:136:in `log_exception': [1mundefined method `response' for #<Errno::ECONNREFUSED: Failed to open TCP connection to aqua.prod.us-west-2.aws.fico.com:443 (Connection refused - connect(2) for 52.89.54.93:443)> ([1;4mNoMethodError[m[1m)[m
[1m          print_debug "#{error.response.request.method.upcase}: #{error.response.request.url}"[m
[1m                              ^^^^^^^^^[m
[1mDid you mean?  respond_to?[m
from /opt/app/toolkit/lib/http.rb:59:in `rescue …
```
=> Only print response if it's a RestClient error

.github/workflows/nativeruby.yml, Containerfile, README.md, lib/kdi/kdi_helpers.rb, tasks/connectors/digital_footprint/bitsight/bitsight.rb, tasks/connectors/lacework/lacework.rb, tasks/connectors/lacework/lib/lacework_helper.rb, tasks/connectors/ms_defender_atp/lib/ms_defender_atp_helper.rb
Lacework's v1 API is deprecated and support for it will be shut off on 1/1/2023.
This PR changes the Lacework endpoints to v2 and makes any related changes necessary for everything to work.
=> Lacework: v1 -> v2 API

tasks/connectors/cobaltio/cobaltio.rb, tasks/connectors/cobaltio/lib/cobaltio_helper.rb
Update the Cobalt.io connector/task in two ways:
1. Add support for "critical" and "informational" severity findings. Without this the connector/task would break if any finding has either of these severities.
2. Update the API requests to always fetch the maximum number of resources possible
=> Update Cobalt.io connector

tasks/connectors/github_dependabot/readme.md
Closes #439
`github_access_token` does not seem to be the correct option for the [`github_dependabot`](https://github.com/KennaSecurity/toolkit/tree/c2ea5b06686a3838aaae9faa1eb8843f077d1527/tasks/connectors/github_dependabot) task.
`github_token` seems to be the correct option.
Looking at the task, the actual name of the option is `github_token`:
https://github.com/KennaSecurity/toolkit/blob/c2ea5b06686a3838aaae9faa1eb8843f077d1527/tasks/connectors/github_dependabot/github_dependabot.rb#L83
Also, when using `github_access_token`, the action output shows this error:
```
docker.io/kennasecurity/toolkit:latest
Running: Kenna::Toolkit::GithubDependabot
[!] (…) Missing! github_token: Github Access Token
[!] (…) Required options missing, cowardly refusing to continue!
```
With `github_token`, …
=> Change `github_access_token` to `github_token`

tasks/connectors/wiz/lib/vulns_mapper.rb
If the platform is aws and we have an instance id we should add that as an ec2 locator for deduplication purposes.
=> add extraction for the ec2 instance id

Gemfile, lib/http.rb, tasks/connectors/lacework/lacework.rb, tasks/connectors/lacework/lib/lacework_helper.rb
Lacework has API rate limiting at the rate of 480 requests per hour. Clients with enough data will hit this and currently the task doesn't have logic to work around this limitation, so the toolkit task will error out.
Added the limiter gem to the toolkit and applied a rate of 480 per hour to get/post methods that retrieve data. Set to spread out requests.
Lacework makes use of a response header "".  This is a draft standard proposal from IETF, so I felt comfortable putting it's use in a shared http utility library of the toolkit provided it's not made required.
=> Lacework rate limits & retry custom wait

Gemfile.lock, tasks/connectors/veracode_findings/lib/veracode_client.rb, tasks/connectors/veracode_findings/veracode_findings.rb
A client has reported that a number of their Kenna findings not closing after subsequent task runs after being resolved in Veracode. The reason seems to be that the findings are just dropping off of the api without ever showing a closed status in the data.  Since the file locators with line number are usually specific to their particular findings, this means we never see the asset again if the findings falls of the api. If we never see the asset again there's no chances for auto-close functionality to take effect.
Provide an optional (to not break anyone's workflow) task option that when set causes us to omit the line number from file locator on non-SCA findings.
=> add omit_line_number option

tasks/connectors/veracode_findings/lib/veracode_client.rb, tasks/connectors/veracode_findings/veracode_findings.rb
Recently implemented omit_line_number option is not in scope where used.
At the beginning of the task run pull it out of the options hash and pass it as an argument into the method where it is used.
=> Veracode findings put omit lines in scope

tasks/connectors/lacework/lacework.rb
With the set of fields the Lacework toolkit task brings in, vulns are scored, but technically informational, and don't have a visible description in the UI
Map in 'description' vuln definition field. Map in 'cve_identifiers' vuln definition field.
- cve description visible in Explore
- vuln description visible on vuln detail page
=> SUP-1171-lacework_map_vuln_description

README.md
README update with usage note regarding new(ish) base64 API keys that contain "$" characters will require escaping when called via shell
=> Toolkit readme update

spec/tasks/connectors/cylera/cylera_task_spec.rb, tasks/connectors/cylera/cylera_task.rb, tasks/connectors/cylera/lib/client.rb, tasks/connectors/cylera/lib/vcr.rb, tasks/connectors/cylera/readme.md
1. Added ability to specify relative time in seconds for time parameters, e.g. cylera_last_seen_after=60s
2. Reversed VCR back as tests are failing without it.
=> Add ability to specify time as delta in seconds for Cylera

spec/tasks/connectors/cylera/cylera_task_spec.rb, tasks/connectors/cylera/cylera_task.rb, tasks/connectors/cylera/readme.md
During client testing it was discovered that a lot of IP addresses are difined incorrectly by Cylera (mostly 0.0.0.0 values).
So, this PR adds new parameter for Cylera task that allows to ignore IP addresses that are included in the provided IP ranges.
=> Add ip_ignore_list to Cylera

tasks/connectors/ntt_sentinel_dynamic/lib/api_client.rb
**Jira**: [SUP-1320](https://kennasecurity.atlassian.net/browse/SUP-1320)
There appears to be a performance a performance issue on the endpoint where we’re requesting data for Whitehat Sentinel pursuant to timeouts, page size changes do not appear to be resolving the issue.
This has been confirmed to be siginficiantly alleviated by changing the parameters to show a more narrow scope of asset information on the /asset endpoint via removing the display_all parameter.
Tracing the code through the connector, and verifying the information we ingest- the information that is lost, is only pursuant to some tags, specifically from the asset hash response we get;
- tags
- asset_owner_name
- custom_asset_id
[SUP-1320]: https://kennasecurity.atlassian.net/browse/SUP-1320?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> SUP 1320 - Remove display_all from sentinel asset query

tasks/connectors/ntt_sentinel_dynamic/ntt_sentinel_dynamic.rb
**Jira**: [SUP-1327](https://kennasecurity.atlassian.net/browse/SUP-1327)
Toolkit sentinel task does not create all assets/applications that reported by sentinel using vuln endpoint
To find/create assets in kdi, we make use of "uniq" method which reads asset hash using string keys, while the asset hash that is provided by the sentinel task uses symbol keys - as a result, the comparison to find the asset is true for every asset but the first ({} == {}) regardless of if they were previously created or not 
Stringify asset hash keys when using create_kdi_asset_finding method as used for vulns defs in create_kdi_vuln_def and similar to lacework connector:
https://github.com/KennaSecurity/toolkit/blob/67f737a103f58be5bee6cd1e13bc678a9888ab7e/tasks/connectors/lacework/lacework.rb#L125C39-L125C53 …
=> Update ntt_sentinel_dynamic.rb to use stringified keys when calling create/find asset kdi helper

tasks/connectors/netsparker/lib/netsparker_client.rb
Netsparker toolkit task gets in an infinite loop when going through paginated results with more than one page, as the page number is increased but the results for new page is not retrieved within the loop, causing page 1 to be parsed indefinitely until the task OOM.
Retrive the new page within the loop.
=> SUP-1348 Get rid of infinite loop while going through paginated results for netsparker

tasks/connectors/wiz/lib/wiz_client.rb
Wiz is returning bad request when querying for issues in toolkit task
The bad request is caused by the action section in serviceTickets included in the issues_query, the use of "action" in serviceTickets is not found in wiz api docs
Remove action section from the query - this is not in use in issues mapper therefore it has no impact
* As per wiz docs, serviceTicket is deprecated and returns null if used, therefore, I'm removing this section and leaving serviceTickets only as part of the clean up
February 2nd, 2023
9 months ago by Joe
Updated: Updated the [Get Issues](https://integrate.wiz.io/reference/issues-query) API query filter serviceTicket to serviceTickets. Using serviceTicket won't break your API, but will return null instead of a value.
=> SUP-1364 Wiz issues query clean up for bad request

tasks/connectors/digital_footprint/bitsight/lib/bitsight_helpers.rb
**Jira**: [SUP-1396](https://kennasecurity.atlassian.net/browse/SUP-1396)
When a SVD identifier over 255 characters is provided by a connector, Kenna truncates the identifier to 255 chars during creation, but fails to update existing SVDs as it attempts to find them based on the untruncated identifier
In toolkit Bitsight task: Truncate vuln_def_name to 246 chars to guarantee identifier in Kenna to be 255 chars max (identifier = scanner_type ("Bitsight " = 9 chars) + vuln_def_name (246 chars) = 255 chars)
[SUP-1396]: https://kennasecurity.atlassian.net/browse/SUP-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Truncate vuln_def_name to 246 chars

tasks/connectors/digital_footprint/bitsight/lib/bitsight_helpers.rb
**Jira**: [SUP-1396](https://kennasecurity.atlassian.net/browse/SUP-1396)
When a SVD identifier over 255 characters is provided by a connector, Kenna truncates the identifier to 255 chars during creation, but fails to update existing SVDs as it attempts to find them based on the untruncated identifier
In toolkit Bitsight task: Truncate cvd name to 246 chars to match vuln_def_name in vuln and to guarantee identifier in Kenna to be 255 chars max (identifier = scanner_type ("Bitsight " = 9 chars) + vuln_def_name (246 chars) = 255 chars)
[SUP-1396]: https://kennasecurity.atlassian.net/browse/SUP-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> truncate cvd name to match vuln_def_name in vuln

tasks/connectors/wiz/lib/wiz_client.rb, tasks/connectors/wiz/readme.md, tasks/connectors/wiz/wiz_task.rb
**Jira**: [SUP-1426](https://kennasecurity.atlassian.net/browse/SUP-1426)
Running wiz task with import_type ALL or ISSUES with default wiz_page_size (5000) results in error "'first' must be less than or equal to 500" during issues import. As per wiz documentation, maximum "first" value for issues is 500 while for vulnerabilities it's 5000.
Implement separate parameters for issues page size and vulnerabilities page size.
[SUP-1426]: https://kennasecurity.atlassian.net/browse/SUP-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SUP-1426 Correct default page size for wiz issues

tasks/connectors/insight_appsec/insight_appsec_task.rb, tasks/connectors/insight_appsec/lib/insight_appsec_client.rb, tasks/connectors/insight_appsec/readme.md
**Jira**: [SUP-1405](https://kennasecurity.atlassian.net/browse/SUP-1405)
Insight Appsec API host is hard coded for US region, while some customers need to make use of other regions
Add a region code parameter to build the API host
[SUP-1405]: https://kennasecurity.atlassian.net/browse/SUP-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SUP-1405 Add region code for Insight Appsec API host

tasks/connectors/qualys_was/README.md, tasks/connectors/qualys_was/qualys_was.rb
The order logic here indicate that we're selecting the svd based on the match between scanner identifier and external_unique_id.
https://github.com/KennaSecurity/beehive/blob/master/lib/beehive/sharded/finding.rb#L85C25-L85C25
@svd = q.where('scanner_vulnerability_definitions.created_at <= ?', created_at)
.order([
'scanner_vulnerability_definitions.identifier = ? DESC',
[external_unique_id]
])
.first
Based on the original mapping in the toolkit, we're providing different vuln_def, vul_def_name then the scanner_identifier which are the 2 elements composing the svd identifier and external_unique_id. This sometimes cause the mismatch of the svd to findings.
Proposing to provide an options in the toolkit to  make the vuln_def / vuln_def_name in the finding hash the same as the …
=> refactor the code with adding options

Gemfile, Gemfile.lock, tasks/connectors/whitesource/lib/whitesource_client.rb, tasks/connectors/whitesource/readme.md, tasks/connectors/whitesource/whitesource_task.rb
Due to Whitesource transitioning to Mend.io, the API version has been updated from 1.3 to 1.4. In version 1.3, we used the static URL:
https://saas.whitesourcesoftware.com/api/v1.3
However, according to Mend.io's documentation (https://docs.mend.io/bundle/api_sca/page/http_api_v1_3_and_v1_4.html) Version 1.4 has the following format
https://(Environment)/api/v1.4
We should request that customers provide their unique API_BASE_URL as a parameter during task execution, The API_BASE_URL can be found in the Mend.io Organization settings, as shown in the example image 
After the code modifications, the task executes successfully.
[SUP-1524]: https://kennasecurity.atlassian.net/browse/SUP-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SUP-1524 Whitesource task API change from v1.3 to v1.4

tasks/connectors/aws_guardduty/aws_guardduty.rb
Output_path variable wasn't declared and it is generating errors 
Using "#{output_dir}/#{filename}" instead
[SUP-1541]: https://kennasecurity.atlassian.net/browse/SUP-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SUP-1541 Fix for undeclared variable on AWS_guardduty.rb toolkit task

tasks/connectors/qualys_was/lib/qualys_was_helper.rb, tasks/connectors/qualys_was/qualys_was.rb
Currently we don't have the check in place if there's empty qid for a single finding, this will result in error in the toolkit task. 
We should skip creating the finding record if the record is invalid for smoother user experiences.
=> SUP-1569-toolkit error out if findings are empty 

tasks/connectors/aqua/aqua.rb, tasks/connectors/aqua/lib/aqua_helper.rb
Trying to connect to Aqua SaaS, near existing authentication logic.
[GitHub Issue](https://github.com/KennaSecurity/toolkit/issues/550#issue-2362548416)
=> Add possibility to do auth for Aqua SaaS near default auth Aqua.

Gemfile.lock, tasks/connectors/wiz/readme.md, tasks/connectors/wiz/wiz_task.rb
Change Wiz import_type default to ISSUES
As per Wiz, Issues contain complete data that needs to be imported, while a Vulnerabilities import might be incomplete and will contain duplicate information if both are done at the same time. Additionally, some Wiz users do not have permissions to retrieve vulnerabilities which is causing the task to fail when default parameters are used. Therefore, we're changing the default import type to ISSUES to avoid conflicting data and so that users don't have to change it manually to run the task.
=> SUP-1730 Change Wiz import type default to ISSUES

.rubocop_todo.yml, tasks/utilities/csv2kdi/csv2kdi.rb, tasks/utilities/csv2kdi/readme.md
**Jira**: [SUP-1780](https://kennasecurity.atlassian.net/browse/SUP-1780)
When a SVD identifier over 255 characters is provided by a connector, Kenna truncates the identifier to 255 chars during creation, but fails to update existing SVDs as it attempts to find them based on the untruncated identifier
In toolkit csv2kdi task: Truncate scanner_id to to guarantee identifier in Kenna to be 255 chars max (identifier = scanner_type + space + scanner_identifier = 255 chars)
[SUP-1780]: https://kennasecurity.atlassian.net/browse/SUP-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SUP-1780 Truncate scanner_id for csv2tkdi toolkit task

.github/workflows/nativeruby.yml, .gitignore, Gemfile, Gemfile.lock, LICENSE.md, README.md, codecov.yml, codeql-analysis.yml, lib/helpers.rb, spec/rspec_helper.rb, spec/tasks/connectors/snyk_v2/snyk_v2_task_spec.rb
PRs for new tasks (connectors) inevitably become something we have to maintain, which is quite difficult without unit tests!
- Change the README to not just encourage specs but require them.
- Add Codecov so PRs immediately have their code coverage delta measured.
- Require every pull request to have ≥ 90% code coverage (limited to the changed lines).
=>  Require code coverage improvement for pull requests

lib/http.rb, spec/rspec_helper.rb
https://kennasecurity.atlassian.net/jira/software/c/projects/SUP/boards/58?selectedIssue=SUP-1778
Following above ticket, we notice that we didn't implement a timeout retry error, hence when there was a timeout on the task, we abort it. Adding this code in for completion
=> SP-1778_add_timeout_retry_error

lib/http.rb
So I realised that we also didn't have the RestClient::Exceptions::OpenTimeout retry logic in the code, 
so I added in in the meantime
=> SUP-1778-adding-opentimeout-to-retry

tasks/connectors/digital_footprint/bitsight/lib/bitsight_helpers.rb
bitsight toolkit tasks is failing for faraday upgrade because http_get methods needs to have valid headers being passed in. 
def my_company
response = http_get("https://#{@bitsight_api_key}:@api.bitsighttech.com/portfolio", {})
portfolio = JSON.parse(response.body)
@companies = portfolio["companies"]
@company_guid = portfolio["my_company"]["guid"]
end
changed the line 
response = http_get("https://#{@bitsight_api_key}:@api.bitsighttech.com/portfolio", {})
to 
response = http_get("https://#{@bitsight_api_key}:@api.bitsighttech.com/portfolio", @headers)
=> SUP-1820-fix bitsight headers

lib/faraday_middlewares/faraday_hmac_middleware.rb, lib/http.rb, tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb
This PR shall fix 2 things: 
1. Veracode is still complaining we're not regenerating new HMAC. 
It looks like the issue is with the middleware order. The HMAC middleware is placed before the retry middleware in the stack, so when retries happen, they reuse the same authorization header without regenerating it.
Adjusting the sequence to see if it will help... 
2. When there's no findings/vulnerabilities on the assets, sometimes the system will fail with error 
opt/app/toolkit/tasks/connectors/veracode_asset_vulns/lib/veracode_av_client.rb:386:in `block in find_missing_kenna_assets': undefined method `none?' for nil:NilClass (NoMethodError)
if @assets.none? { |new_assets| new_assets["file"] == a["file"] }
^^^^^^
Reasons can be below:
When @assets IS nil (error occurs):
1. No scan types …
=> SUP-1778-HMAC-generation-adjustment
